### ISSUE TITLE
Support Python 3.11, 3.12

### ISSUE THREAD

**Issue by simon-liebehenschel** [pietrodn/cloud-profiler-python-wheels#3]
Will you add this soon? Otherwise I will build for myself locally.

**Comment by pietrodn** [comment]
I tried in the past but didn't succeed for python 3.11. Trying again.

**Comment by pietrodn** [comment]
3.11 wheels are out, updating `cibuildwheel` to build for 3.12... ⚙️

**Comment by pietrodn** [comment]
Python 3.12 wheels are out as well! Can you please test them? https://github.com/pietrodn/cloud-profiler-python-wheels/releases/tag/4.1.0
